### ISSUE TITLE
SIGILL: illegal instruction

### ISSUE THREAD

**Issue by SonnySon17** [simnalamburt/macos-totp-cli#1]
설치 후 

`totp scan vpn ./fortivpn.jpg` 

커멘드 실행하면

```
SIGILL: illegal instruction
PC=0x7fff408d880a m=0 sigcode=1
instruction bytes: 0xf 0xb 0x48 0x89 0xf0 0x48 0x89 0xf9 0xf6 0xc1 0x1 0x75 0x63 0x48 0x8b 0x11

goroutine 0 [idle]:
runtime: unknown pc 0x7fff408d880a
stack: frame={sp:0x7ffeefbff690, fp:0x0} stack=[0x7ffeefb807e8,0x7ffeefbff850)
0x00007ffeefbff590:  0x00000000044ed600  0x00000000044e9a00
0x00007ffeefbff5a0:  0x00007ffeefbff650  0x00007fff6cba643b
0x00007ffeefbff5b0:  0x0000000000000000  0xf69d800070001006
0x00007ffeefbff5c0:  0x00000000044effff  0x0000000000000000
0x00007ffeefbff5d0:  0x0000000000000040  0x0000000000000040
0x00007ffeefbff5e0:  0x0000000000000007  0x00000000044e6000
0x00007ffeefbff5f0:  0x00007ffeefbff620  0x00007fff6cba620f
0x00007ffeefbff600:  0x0000000000003c00  0x00007fff9bab2920
0x00007ffeefbff610:  0x00007fffa3035000  0x0000000600000000
0x00007ffeefbff620:  0x00000000044e7080  0x0000000000000003
0x00007ffeefbff630:  0x0000000000000068  0x0000000000000068
0x00007ffeefbff640:  0x0000000000000000  0x00000000044e6000
0x00007ffeefbff650:  0x00007ffeefbff680  0x00007fff6cba620f
0x00007ffeefbff660:  0x0000000000000003  0x000000000000000d
0x00007ffeefbff670:  0x00007fffa3035000  0x0000000000000068
0x00007ffeefbff680:  0x00007ffeefbff6b0  0x00007fff6cba4c99
0x00007ffeefbff690: <0x00007ffeefbff6e0  0x00007fff409ccda6
0x00007ffeefbff6a0:  0x00007fff9bbe7168  0x0000000000000000
0x00007ffeefbff6b0:  0x00000000053004b0  0x0000000000000004
0x00007ffeefbff6c0:  0x0000000000000000  0x0000000005300200
0x00007ffeefbff6d0:  0x0000000000000000  0x000000000000000d
0x00007ffeefbff6e0:  0x00007ffeefbff760  0x00007fff408d7a1a
0x00007ffeefbff6f0:  0x0000000000000000  0x0000000000000000
0x00007ffeefbff700:  0x0000000000000000  0x0000000005300200
0x00007ffeefbff710:  0x00007fff408d87ea  0x000000000000000d
0x00007ffeefbff720:  0x00000000053005b0  0x00000000053004b0
0x00007ffeefbff730:  0x0000000000000004  0x0000000000000000
0x00007ffeefbff740:  0x000000c000016300  0x00000000053005b0
0x00007ffeefbff750:  0x0000000000000007  0x000000c000016340
0x00007ffeefbff760:  0x00007ffeefbff7a0  0x00007fff408dadd0
0x00007ffeefbff770:  0x000000c0001fe000  0x000000c0001fd768
0x00007ffeefbff780:  0x000000c0001fd9d8  0x000000c0001fd950
runtime: unknown pc 0x7fff408d880a
stack: frame={sp:0x7ffeefbff690, fp:0x0} stack=[0x7ffeefb807e8,0x7ffeefbff850)
0x00007ffeefbff590:  0x00000000044ed600  0x00000000044e9a00
0x00007ffeefbff5a0:  0x00007ffeefbff650  0x00007fff6cba643b
0x00007ffeefbff5b0:  0x0000000000000000  0xf69d800070001006
0x00007ffeefbff5c0:  0x00000000044effff  0x0000000000000000
0x00007ffeefbff5d0:  0x0000000000000040  0x0000000000000040
0x00007ffeefbff5e0:  0x0000000000000007  0x00000000044e6000
0x00007ffeefbff5f0:  0x00007ffeefbff620  0x00007fff6cba620f
0x00007ffeefbff600:  0x0000000000003c00  0x00007fff9bab2920
0x00007ffeefbff610:  0x00007fffa3035000  0x0000000600000000
0x00007ffeefbff620:  0x00000000044e7080  0x0000000000000003
0x00007ffeefbff630:  0x0000000000000068  0x0000000000000068
0x00007ffeefbff640:  0x0000000000000000  0x00000000044e6000
0x00007ffeefbff650:  0x00007ffeefbff680  0x00007fff6cba620f
0x00007ffeefbff660:  0x0000000000000003  0x000000000000000d
0x00007ffeefbff670:  0x00007fffa3035000  0x0000000000000068
0x00007ffeefbff680:  0x00007ffeefbff6b0  0x00007fff6cba4c99
0x00007ffeefbff690: <0x00007ffeefbff6e0  0x00007fff409ccda6
0x00007ffeefbff6a0:  0x00007fff9bbe7168  0x0000000000000000
0x00007ffeefbff6b0:  0x00000000053004b0  0x0000000000000004
0x00007ffeefbff6c0:  0x0000000000000000  0x0000000005300200
0x00007ffeefbff6d0:  0x0000000000000000  0x000000000000000d
0x00007ffeefbff6e0:  0x00007ffeefbff760  0x00007fff408d7a1a
0x00007ffeefbff6f0:  0x0000000000000000  0x0000000000000000
0x00007ffeefbff700:  0x0000000000000000  0x0000000005300200
0x00007ffeefbff710:  0x00007fff408d87ea  0x000000000000000d
0x00007ffeefbff720:  0x00000000053005b0  0x00000000053004b0
0x00007ffeefbff730:  0x0000000000000004  0x0000000000000000
0x00007ffeefbff740:  0x000000c000016300  0x00000000053005b0
0x00007ffeefbff750:  0x0000000000000007  0x000000c000016340
0x00007ffeefbff760:  0x00007ffeefbff7a0  0x00007fff408dadd0
0x00007ffeefbff770:  0x000000c0001fe000  0x000000c0001fd768
0x00007ffeefbff780:  0x000000c0001fd9d8  0x000000c0001fd950

goroutine 1 [syscall]:
runtime.cgocall(0x41a5890, 0xc0001fd768)
	/usr/local/Cellar/go/1.17.8/libexec/src/runtime/cgocall.go:156 +0x5c fp=0xc0001fd740 sp=0xc0001fd708 pc=0x400527c
github.com/keybase/go-keychain._Cfunc_CFDictionaryCreateSafe2(0x0, 0xc000016300, 0xc000016340, 0x7, 0x7fff9bab3d60, 0x7fff9bab3dc0)
	_cgo_gotypes.go:584 +0x4d fp=0xc0001fd768 sp=0xc0001fd740 pc=0x40fd80d
github.com/keybase/go-keychain.MapToCFDictionary.func1(0xc0001fd878, 0xc00001b240, 0xc0001fd878)
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/keybase/go-keychain@v0.0.0-20201121013009-976c83ec27a6/corefoundation.go:81 +0xcf fp=0xc0001fd7e0 sp=0xc0001fd768 pc=0x40fe96f
github.com/keybase/go-keychain.MapToCFDictionary(0xc0001fda58)
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/keybase/go-keychain@v0.0.0-20201121013009-976c83ec27a6/corefoundation.go:81 +0x1c5 fp=0xc0001fd8e8 sp=0xc0001fd7e0 pc=0x40fe825
github.com/keybase/go-keychain.ConvertMapToCFDictionary(0x4448640)
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/keybase/go-keychain@v0.0.0-20201121013009-976c83ec27a6/corefoundation.go:218 +0x64c fp=0xc0001fdac8 sp=0xc0001fd8e8 pc=0x40ff84c
github.com/keybase/go-keychain.AddItem({0x41cf640})
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/keybase/go-keychain@v0.0.0-20201121013009-976c83ec27a6/keychain.go:358 +0x34 fp=0xc0001fdb20 sp=0xc0001fdac8 pc=0x41000d4
main.addItem({0x7ffeefbffa42, 0xc000151480}, {0xc0000741a7, 0x1a})
	/private/tmp/totp-20220314-6338-11cbt0q/macos-totp-cli-1.0.0/main.go:32 +0x465 fp=0xc0001fdcd8 sp=0xc0001fdb20 pc=0x41a4045
main.main.func1(0xc000154280, {0xc000064700, 0x2, 0x2})
	/private/tmp/totp-20220314-6338-11cbt0q/macos-totp-cli-1.0.0/main.go:80 +0x1c5 fp=0xc0001fdd60 sp=0xc0001fdcd8 pc=0x41a4645
github.com/spf13/cobra.(*Command).execute(0xc000154280, {0xc0000646c0, 0x2, 0x2})
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e fp=0xc0001fde20 sp=0xc0001fdd60 pc=0x4193cee
github.com/spf13/cobra.(*Command).ExecuteC(0xc000154f00)
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc fp=0xc0001fded8 sp=0xc0001fde20 pc=0x41943dc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sangrakson/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/private/tmp/totp-20220314-6338-11cbt0q/macos-totp-cli-1.0.0/main.go:192 +0x35d fp=0xc0001fdf80 sp=0xc0001fded8 pc=0x41a43fd
runtime.main()
	/usr/local/Cellar/go/1.17.8/libexec/src/runtime/proc.go:255 +0x227 fp=0xc0001fdfe0 sp=0xc0001fdf80 pc=0x4036f27
runtime.goexit()
	/usr/local/Cellar/go/1.17.8/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001fdfe8 sp=0xc0001fdfe0 pc=0x4061f61

rax    0x7fff40c54238
rbx    0x4
rcx    0x7fff408d87ea
rdx    0x100000380
rdi    0x7fff9bab2920
rsi    0x0
rbp    0x7ffeefbff690
rsp    0x7ffeefbff690
r8     0x53005b0
r9     0x53004b0
r10    0x89eb801e3
r11    0xa5baadb9
r12    0x53005b0
r13    0x5300200
r14    0x53004b0
r15    0x0
rip    0x7fff408d880a
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
```

와 같이 떨어지네요ㅠㅠ

관련해서 혹시 제 로컬 설정문제인가 하고 찾아봐도 명확한 해결법을 못찾는중입니다...

https://github.com/golang/go/issues/37459
https://github.com/golang/go/issues/30186
https://github.com/filecoin-project/lotus/issues/2332
https://developer.apple.com/forums/thread/681168

**Comment by simnalamburt** [comment]
Please check whether you downloaded the x86_64 binary to the ARM MacBook or the ARM binary to the Intel MacBook.

**Comment by simnalamburt** [comment]
Update: I've built totp Homebrew bottle for both Intel and M1. Try the following installation method instead:

```bash
brew install simnalamburt/x/totp
```

###### References
- https://github.com/simnalamburt/homebrew-x/releases/tag/totp-1.0.0
